// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlshapicrrhppotcvmkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsc2hhcGljcnJocHBvdGN2bWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTYyMDUsImV4cCI6MjA3NDAzMjIwNX0._cJQbiIGKNpefXI3xHs1yvH4Yr94GuCbiJN1a5ixT0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});